version: '3.8'

services:
  grafana:
    image: grafana/grafana:9.5.1-ubuntu
    container_name: grafana
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.sample.co
      - GF_SERVER_DOMAIN=grafana.sample.co
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.grafana.entrypoints=http,https"
      - "traefik.http.routers.grafana.rule=Host(`grafana.sample.co`)"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  grafana-data:
